# Generated by Django 4.0.2 on 2022-03-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(max_length=100, verbose_name='Прием пищи')),
            ],
            options={
                'verbose_name': 'Прием пищи',
                'verbose_name_plural': 'Приемы пищи',
                'ordering': ('meal_time',),
            },
        ),
        migrations.CreateModel(
            name='MenuDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_day_date', models.DateField(verbose_name='Дата меню')),
            ],
            options={
                'verbose_name': 'День меню',
                'verbose_name_plural': 'Дни меню',
                'ordering': ('menu_day_date',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('reduction_factor', models.FloatField(verbose_name='Коэффициент уменьшения при приготовлении')),
            ],
            options={
                'verbose_name': 'Продукт питания',
                'verbose_name_plural': 'Продукты питания',
                'ordering': ('product_name',),
            },
        ),
        migrations.CreateModel(
            name='ProductsInRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count_gross', models.FloatField(verbose_name='Масса брутто продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в технологической карте',
                'verbose_name_plural': 'Продукты в технологической карте',
                'ordering': ('routing',),
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_name', models.CharField(max_length=255, verbose_name='Название технологической карты')),
                ('product', models.ManyToManyField(through='menu.ProductsInRouting', to='menu.Product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Технологическая карта',
                'verbose_name_plural': 'Технологические карты',
                'ordering': ('routing_name',),
            },
        ),
        migrations.CreateModel(
            name='RoutingInMenuDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.mealtime', verbose_name='Прием пищи')),
                ('menu_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuday', verbose_name='День в меню')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.routing', verbose_name='Технологическая карта')),
            ],
            options={
                'verbose_name': 'Технологическая карта в меню',
                'verbose_name_plural': 'Технологические карты в меню',
                'ordering': ('menu_day',),
            },
        ),
        migrations.AddField(
            model_name='productsinrouting',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.routing', verbose_name='Технологическая карта'),
        ),
        migrations.AddField(
            model_name='menuday',
            name='technological_maps',
            field=models.ManyToManyField(through='menu.RoutingInMenuDay', to='menu.Routing', verbose_name='Технологические карты'),
        ),
    ]
