# Generated by Django 4.0.2 on 2022-03-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routing',
            new_name='Map',
        ),
    ]
