# Generated by Django 4.0.2 on 2022-03-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_routing_map'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsInRouting',
            new_name='ProductsInMap',
        ),
    ]
