# Generated by Django 4.0.2 on 2022-03-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_productsinrouting_productsinmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapsInMenuDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Технологическая карта в меню',
                'verbose_name_plural': 'Технологические карты в меню',
                'ordering': ('menu_day',),
            },
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ('map_name',), 'verbose_name': 'Технологическая карта', 'verbose_name_plural': 'Технологические карты'},
        ),
        migrations.AlterModelOptions(
            name='productsinmap',
            options={'ordering': ('map',), 'verbose_name': 'Продукт в технологической карте', 'verbose_name_plural': 'Продукты в технологической карте'},
        ),
        migrations.RenameField(
            model_name='map',
            old_name='routing_name',
            new_name='map_name',
        ),
        migrations.RenameField(
            model_name='productsinmap',
            old_name='routing',
            new_name='map',
        ),
        migrations.AlterField(
            model_name='menuday',
            name='technological_maps',
            field=models.ManyToManyField(through='menu.MapsInMenuDay', to='menu.Map', verbose_name='Технологические карты'),
        ),
        migrations.DeleteModel(
            name='RoutingInMenuDay',
        ),
        migrations.AddField(
            model_name='mapsinmenuday',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.map', verbose_name='Технологическая карта'),
        ),
        migrations.AddField(
            model_name='mapsinmenuday',
            name='meal_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.mealtime', verbose_name='Прием пищи'),
        ),
        migrations.AddField(
            model_name='mapsinmenuday',
            name='menu_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuday', verbose_name='День в меню'),
        ),
    ]
