# Generated by Django 4.0.2 on 2022-03-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_map_map_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание технологического процесса'),
        ),
    ]
