# Generated by Django 4.0.2 on 2022-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_map_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuday',
            name='menu_day_date',
            field=models.DateField(unique=True, verbose_name='Дата меню'),
        ),
    ]
