# Generated by Django 4.0.2 on 2022-04-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_productgroup_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='norm_per_day',
            field=models.FloatField(default=1, verbose_name='Норма на одного человека в сутки (брутто, грамм)'),
            preserve_default=False,
        ),
    ]
