# Generated by Django 4.0.2 on 2022-04-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_productgroup_norm_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_category', models.CharField(max_length=100, verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name': 'Категория блюда',
                'verbose_name_plural': 'Категории блюд',
                'ordering': ('dish_category',),
            },
        ),
        migrations.CreateModel(
            name='TreatmentKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_kind', models.CharField(max_length=100, verbose_name='Вид обработки')),
            ],
            options={
                'verbose_name': 'Вид обработки',
                'verbose_name_plural': 'Виды обработки',
                'ordering': ('treatment_kind',),
            },
        ),
    ]
