# Generated by Django 4.0.2 on 2022-04-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_daterange_remove_product_reduction_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinmap',
            name='treatments',
            field=models.ManyToManyField(blank=True, null=True, to='menu.TreatmentKind', verbose_name='Обработки продукта'),
        ),
    ]
