# Generated by Django 4.0.2 on 2022-04-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_productsinmap_treatments'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(default=0, verbose_name='Углеводы, 100 г. (Нетто)'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_value',
            field=models.FloatField(default=0, verbose_name='Энергетическая ценность (кКал), 100 г. (Брутто)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.FloatField(default=0, verbose_name='Жиры, 100 г. (Нетто)'),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.FloatField(default=0, verbose_name='Белки, 100 г. (Нетто)'),
        ),
    ]
