# Generated by Django 4.0.2 on 2022-04-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_product_carbohydrates_product_energy_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastageByHeatTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_value_wastage', models.FloatField(default=0, verbose_name='Потеря энергетическая ценности')),
                ('proteins_wastage', models.FloatField(default=0, verbose_name='Потеря белка')),
                ('fats_wastage', models.FloatField(default=0, verbose_name='Потеря жиров')),
                ('carbohydrates_wastage', models.FloatField(default=0, verbose_name='Потеря углеводов')),
            ],
            options={
                'verbose_name': 'Потеря при тепловой обработке (энергетическая ценность, белки, жиры, углеводы)',
                'verbose_name_plural': 'Потери при тепловой обработке (энергетическая ценность, белки, жиры, углеводы)',
                'ordering': ('id',),
            },
        ),
    ]
