# Generated by Django 4.0.2 on 2022-04-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_wastagebyheattreatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentkind',
            name='is_heat_treatment',
            field=models.BooleanField(default=False, verbose_name='Учесть потери белков, жиров и углеводов'),
        ),
        migrations.AlterField(
            model_name='productsinmap',
            name='treatments',
            field=models.ManyToManyField(blank=True, to='menu.TreatmentKind', verbose_name='Обработки продукта'),
        ),
        migrations.AlterField(
            model_name='wastagebyheattreatment',
            name='carbohydrates_wastage',
            field=models.FloatField(default=0, verbose_name='Потеря углеводов, %'),
        ),
        migrations.AlterField(
            model_name='wastagebyheattreatment',
            name='energy_value_wastage',
            field=models.FloatField(default=0, verbose_name='Потеря энергетическая ценности, %'),
        ),
        migrations.AlterField(
            model_name='wastagebyheattreatment',
            name='fats_wastage',
            field=models.FloatField(default=0, verbose_name='Потеря жиров, %'),
        ),
        migrations.AlterField(
            model_name='wastagebyheattreatment',
            name='proteins_wastage',
            field=models.FloatField(default=0, verbose_name='Потеря белка, %'),
        ),
    ]
