# Generated by Django 4.0.2 on 2022-04-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_treatmentkind_is_heat_treatment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='product',
            new_name='products',
        ),
    ]
