# Generated by Django 4.0.2 on 2022-04-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_rename_product_map_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='group_name',
            field=models.CharField(max_length=255, verbose_name='Название группы'),
        ),
    ]
