# Generated by Django 4.0.2 on 2022-04-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_productgroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
    ]
