# Generated by Django 4.0.2 on 2022-04-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_productsinmap_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='replacements',
            field=models.ManyToManyField(blank=True, to='menu.ProductGroup', verbose_name='Замены'),
        ),
    ]
