# Generated by Django 4.0.2 on 2022-04-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_productgroup_replacements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='replacements',
        ),
    ]
