# Generated by Django 4.0.2 on 2022-04-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_productgroup_replacement_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementForProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_count', models.IntegerField(verbose_name='Норма по замене не 100 г. продукта')),
            ],
            options={
                'verbose_name': 'Замена групп',
                'verbose_name_plural': 'Замены групп',
                'ordering': ('main_product_group',),
            },
        ),
        migrations.AddField(
            model_name='productgroup',
            name='replacements',
            field=models.ManyToManyField(through='menu.ReplacementForProductGroup', to='menu.ProductGroup', verbose_name='Замены'),
        ),
        migrations.AddField(
            model_name='replacementforproductgroup',
            name='main_product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.productgroup', verbose_name='Основная группа продуктов'),
        ),
        migrations.AddField(
            model_name='replacementforproductgroup',
            name='replacing_product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacing_product_group', to='menu.productgroup', verbose_name='Заменяется группой продуктов'),
        ),
    ]
