# Generated by Django 4.0.2 on 2022-04-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_alter_productgroup_replacement_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='replacement_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.productgroup', verbose_name='Является заменой для'),
        ),
    ]
