# Generated by Django 4.0.2 on 2022-04-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_alter_productgroup_replacement_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastagebydaterange',
            name='percent',
            field=models.FloatField(default=0, verbose_name='Потеря, %'),
        ),
    ]
