# Generated by Django 4.0.2 on 2022-04-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_alter_wastagebydaterange_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinmap',
            name='product_count_gross_normalize',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса брутто продукта (нормализованная)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(default=0, verbose_name='Углеводы, 100 г.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_value',
            field=models.FloatField(default=0, verbose_name='Энергетическая ценность (кКал), 100 г.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(default=0, verbose_name='Жиры, 100 г.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(default=0, verbose_name='Белки, 100 г.'),
        ),
    ]
